module.exports = [
	{ Country: 'Guernsey (GG)', Zone: 'zone1' },
	{ Country: 'Ireland, Rep. Of (IE)', Zone: 'zone1' },
	{ Country: 'Jersey (JE)', Zone: 'zone1' },
	{ Country: 'United Kingdom (GB)', Zone: 'zone1' },
	{ Country: 'Benin (BJ)', Zone: 'zone2' },
	{ Country: 'Burkina Faso (BF)', Zone: 'zone2' },
	{ Country: 'Cameroon (CM)', Zone: 'zone2' },
	{ Country: 'Cape Verde (CV)', Zone: 'zone2' },
	{ Country: 'Central African Rep(CF)', Zone: 'zone2' },
	{ Country: 'Chad (TD)', Zone: 'zone2' },
	{ Country: 'Congo (CG)', Zone: 'zone2' },
	{ Country: 'Congo, DPR (CD)', Zone: 'zone2' },
	{ Country: 'Cote D Ivoire (CI)', Zone: 'zone2' },
	{ Country: 'Gabon (GA)', Zone: 'zone2' },
	{ Country: 'Gambia (GM)', Zone: 'zone2' },
	{ Country: 'Ghana (GH)', Zone: 'zone2' },
	{ Country: 'Guinea Rep. (GN)', Zone: 'zone2' },
	{ Country: 'Guinea-Bissau (GW)', Zone: 'zone2' },
	{ Country: 'Guinea-Equatorial (GQ)', Zone: 'zone2' },
	{ Country: 'Liberia (LR)', Zone: 'zone2' },
	{ Country: 'Mali (ML)', Zone: 'zone2' },
	{ Country: 'Niger (NE)', Zone: 'zone2' },
	{ Country: 'Sao Tome And Principe (ST)', Zone: 'zone2' },
	{ Country: 'Senegal (SN)', Zone: 'zone2' },
	{ Country: 'Sierra Leone (SL)', Zone: 'zone2' },
	{ Country: 'Togo (TG)', Zone: 'zone2' },
	{ Country: 'Canada (CA)', Zone: 'zone3' },
	{ Country: 'Mexico (MX)', Zone: 'zone3' },
	{ Country: 'USA (US)', Zone: 'zone3' },
	{ Country: 'Albania (AL)', Zone: 'zone4' },
	{ Country: 'Andorra (AD)', Zone: 'zone4' },
	{ Country: 'Austria (AT)', Zone: 'zone4' },
	{ Country: 'Belarus (BY)', Zone: 'zone4' },
	{ Country: 'Belgium (BE)', Zone: 'zone4' },
	{ Country: 'Bosnia & Herzegovina(BA)', Zone: 'zone4' },
	{ Country: 'Bulgaria (BG)', Zone: 'zone4' },
	{ Country: 'Canary Islands, The (IC)', Zone: 'zone4' },
	{ Country: 'Croatia (HR)', Zone: 'zone4' },
	{ Country: 'Cyprus (CY)', Zone: 'zone4' },
	{ Country: 'Czech Rep., The (CZ)', Zone: 'zone4' },
	{ Country: 'Denmark (DK)', Zone: 'zone4' },
	{ Country: 'Estonia (EE)', Zone: 'zone4' },
	{ Country: 'Faroe Islands (FO)', Zone: 'zone4' },
	{ Country: 'Finland (FI)', Zone: 'zone4' },
	{ Country: 'France (FR)', Zone: 'zone4' },
	{ Country: 'Germany (DE)', Zone: 'zone4' },
	{ Country: 'Gibraltar (GI)', Zone: 'zone4' },
	{ Country: 'Greece (GR)', Zone: 'zone4' },
	{ Country: 'Greenland (GL)', Zone: 'zone4' },
	{ Country: 'Hungary (HU)', Zone: 'zone4' },
	{ Country: 'Iceland (IS)', Zone: 'zone4' },
	{ Country: 'Italy (IT)', Zone: 'zone4' },
	{ Country: 'Kosovo (KV)', Zone: 'zone4' },
	{ Country: 'Latvia (LV)', Zone: 'zone4' },
	{ Country: 'Liechtenstein (LI)', Zone: 'zone4' },
	{ Country: 'Lithuania (LT)', Zone: 'zone4' },
	{ Country: 'Luxembourg (LU)', Zone: 'zone4' },
	{ Country: 'Malta (MT)', Zone: 'zone4' },
	{ Country: 'Moldova, Rep. Of (MD)', Zone: 'zone4' },
	{ Country: 'Monaco (MC)', Zone: 'zone4' },
	{ Country: 'Montenegro, Rep Of (ME)', Zone: 'zone4' },
	{ Country: 'Netherlands, The (NL)', Zone: 'zone4' },
	{ Country: 'North Macedonia (MK)', Zone: 'zone4' },
	{ Country: 'Norway (NO)', Zone: 'zone4' },
	{ Country: 'Poland (PL)', Zone: 'zone4' },
	{ Country: 'Portugal (PT)', Zone: 'zone4' },
	{ Country: 'Romania (RO)', Zone: 'zone4' },
	{ Country: 'Russian Federation (RU)', Zone: 'zone4' },
	{ Country: 'San Marino (SM)', Zone: 'zone4' },
	{ Country: 'Serbia, Rep. Of (RS)', Zone: 'zone4' },
	{ Country: 'Slovakia (SK)', Zone: 'zone4' },
	{ Country: 'Slovenia (SI)', Zone: 'zone4' },
	{ Country: 'Spain (ES)', Zone: 'zone4' },
	{ Country: 'Sweden (SE)', Zone: 'zone4' },
	{ Country: 'Switzerland (CH)', Zone: 'zone4' },
	{ Country: 'Turkey (TR)', Zone: 'zone4' },
	{ Country: 'Ukraine (UA)', Zone: 'zone4' },
	{ Country: 'Vatican City (VA)', Zone: 'zone4' },
	{ Country: 'Algeria (DZ)', Zone: 'zone5' },
	{ Country: 'Angola (AO)', Zone: 'zone5' },
	{ Country: 'Botswana (BW)', Zone: 'zone5' },
	{ Country: 'Burundi (BI)', Zone: 'zone5' },
	{ Country: 'Comoros (KM)', Zone: 'zone5' },
	{ Country: 'Djibouti (DJ)', Zone: 'zone5' },
	{ Country: 'Egypt (EG)', Zone: 'zone5' },
	{ Country: 'Eritrea (ER)', Zone: 'zone5' },
	{ Country: 'Eswatini (SZ)', Zone: 'zone5' },
	{ Country: 'Ethiopia (ET)', Zone: 'zone5' },
	{ Country: 'Kenya (KE)', Zone: 'zone5' },
	{ Country: 'Lesotho (LS)', Zone: 'zone5' },
	{ Country: 'Libya (LY)', Zone: 'zone5' },
	{ Country: 'Madagascar (MG)', Zone: 'zone5' },
	{ Country: 'Malawi (MW)', Zone: 'zone5' },
	{ Country: 'Mauritania (MR)', Zone: 'zone5' },
	{ Country: 'Mauritius (MU)', Zone: 'zone5' },
	{ Country: 'Mayotte (YT)', Zone: 'zone5' },
	{ Country: 'Morocco (MA)', Zone: 'zone5' },
	{ Country: 'Mozambique (MZ)', Zone: 'zone5' },
	{ Country: 'Namibia (NA)', Zone: 'zone5' },
	{ Country: 'Reunion, Island Of (RE)', Zone: 'zone5' },
	{ Country: 'Rwanda (RW)', Zone: 'zone5' },
	{ Country: 'Seychelles (SC)', Zone: 'zone5' },
	{ Country: 'Somalia (SO)', Zone: 'zone5' },
	{ Country: 'Somaliland, Rep Of (XS)', Zone: 'zone5' },
	{ Country: 'South Africa (ZA)', Zone: 'zone5' },
	{ Country: 'South Sudan (SS)', Zone: 'zone5' },
	{ Country: 'Sudan (SD)', Zone: 'zone5' },
	{ Country: 'Tanzania (TZ)', Zone: 'zone5' },
	{ Country: 'Tunisia (TN)', Zone: 'zone5' },
	{ Country: 'Uganda (UG)', Zone: 'zone5' },
	{ Country: 'Zambia (ZM)', Zone: 'zone5' },
	{ Country: 'Zimbabwe (ZW)', Zone: 'zone5' },
	{ Country: 'Afghanistan (AF)', Zone: 'zone6' },
	{ Country: 'Bahrain (BH)', Zone: 'zone6' },
	{ Country: 'Iran (IR)', Zone: 'zone6' },
	{ Country: 'Iraq (IQ)', Zone: 'zone6' },
	{ Country: 'Israel (IL)', Zone: 'zone6' },
	{ Country: 'Jordan (JO)', Zone: 'zone6' },
	{ Country: 'Kuwait (KW)', Zone: 'zone6' },
	{ Country: 'Lebanon (LB)', Zone: 'zone6' },
	{ Country: 'Oman (OM)', Zone: 'zone6' },
	{ Country: 'Qatar (QA)', Zone: 'zone6' },
	{ Country: 'Saudi Arabia (SA)', Zone: 'zone6' },
	{ Country: 'Syria (SY)', Zone: 'zone6' },
	{ Country: 'United Arab Emirates (AE)', Zone: 'zone6' },
	{ Country: 'Yemen, Rep. Of (YE)', Zone: 'zone6' },
	{ Country: 'Armenia (AM)', Zone: 'zone7' },
	{ Country: 'Australia (AU)', Zone: 'zone7' },
	{ Country: 'Azerbaijan (AZ)', Zone: 'zone7' },
	{ Country: 'Bangladesh (BD)', Zone: 'zone7' },
	{ Country: 'Bhutan (BT)', Zone: 'zone7' },
	{ Country: 'Brunei (BN)', Zone: 'zone7' },
	{ Country: 'Cambodia (KH)', Zone: 'zone7' },
	{ Country: 'China (CN)', Zone: 'zone7' },
	{ Country: 'Georgia (GE)', Zone: 'zone7' },
	{ Country: 'Hong Kong SAR China (HK)', Zone: 'zone7' },
	{ Country: 'India (IN)', Zone: 'zone7' },
	{ Country: 'Indonesia (ID)', Zone: 'zone7' },
	{ Country: 'Japan (JP)', Zone: 'zone7' },
	{ Country: 'Kazakhstan (KZ)', Zone: 'zone7' },
	{ Country: 'Korea, Rep. Of (KR)', Zone: 'zone7' },
	{ Country: 'Korea,  D.P.R Of (KP)', Zone: 'zone7' },
	{ Country: 'Kyrgyzstan (KG)', Zone: 'zone7' },
	{ Country: 'Laos (LA)', Zone: 'zone7' },
	{ Country: 'Macau SAR China (MO)', Zone: 'zone7' },
	{ Country: 'Malaysia (MY)', Zone: 'zone7' },
	{ Country: 'Maldives (MV)', Zone: 'zone7' },
	{ Country: 'Mongolia (MN)', Zone: 'zone7' },
	{ Country: 'Myanmar (MM)', Zone: 'zone7' },
	{ Country: 'Nepal (NP)', Zone: 'zone7' },
	{ Country: 'Pakistan (PK)', Zone: 'zone7' },
	{ Country: 'Palau (PW)', Zone: 'zone7' },
	{ Country: 'Philippines, The (PH)', Zone: 'zone7' },
	{ Country: 'Singapore (SG)', Zone: 'zone7' },
	{ Country: 'Sri Lanka (LK)', Zone: 'zone7' },
	{ Country: 'Taiwan (TW)', Zone: 'zone7' },
	{ Country: 'Tajikistan (TJ)', Zone: 'zone7' },
	{ Country: 'Thailand (TH)', Zone: 'zone7' },
	{ Country: 'Timor-Leste (TL)', Zone: 'zone7' },
	{ Country: 'Turkmenistan (TM)', Zone: 'zone7' },
	{ Country: 'Uzbekistan (UZ)', Zone: 'zone7' },
	{ Country: 'Vietnam (VN)', Zone: 'zone7' },
	{ Country: 'American Samoa (AS)', Zone: 'zone8' },
	{ Country: 'Anguilla (AI)', Zone: 'zone8' },
	{ Country: 'Antigua (AG)', Zone: 'zone8' },
	{ Country: 'Argentina (AR)', Zone: 'zone8' },
	{ Country: 'Aruba (AW)', Zone: 'zone8' },
	{ Country: 'Bahamas (BS)', Zone: 'zone8' },
	{ Country: 'Barbados (BB)', Zone: 'zone8' },
	{ Country: 'Belize (BZ)', Zone: 'zone8' },
	{ Country: 'Bermuda (BM)', Zone: 'zone8' },
	{ Country: 'Bolivia (BO)', Zone: 'zone8' },
	{ Country: 'Bonaire (XB)', Zone: 'zone8' },
	{ Country: 'Brazil (BR)', Zone: 'zone8' },
	{ Country: 'Cayman Islands (KY)', Zone: 'zone8' },
	{ Country: 'Chile (CL)', Zone: 'zone8' },
	{ Country: 'Colombia (CO)', Zone: 'zone8' },
	{ Country: 'Cook Islands (CK)', Zone: 'zone8' },
	{ Country: 'Costa Rica (CR)', Zone: 'zone8' },
	{ Country: 'Cuba (CU)', Zone: 'zone8' },
	{ Country: 'Curacao (XC)', Zone: 'zone8' },
	{ Country: 'Dominica (DM)', Zone: 'zone8' },
	{ Country: 'Dominican Rep. (DO)', Zone: 'zone8' },
	{ Country: 'Ecuador (EC)', Zone: 'zone8' },
	{ Country: 'El Salvador (SV)', Zone: 'zone8' },
	{ Country: 'Falkland Islands (FK)', Zone: 'zone8' },
	{ Country: 'Fiji (FJ)', Zone: 'zone8' },
	{ Country: 'French Guyana (GF)', Zone: 'zone8' },
	{ Country: 'Grenada (GD)', Zone: 'zone8' },
	{ Country: 'Guadeloupe (GP)', Zone: 'zone8' },
	{ Country: 'Guam (GU)', Zone: 'zone8' },
	{ Country: 'Guatemala (GT)', Zone: 'zone8' },
	{ Country: 'Guyana-British (GY)', Zone: 'zone8' },
	{ Country: 'Haiti (HT)', Zone: 'zone8' },
	{ Country: 'Honduras (HN)', Zone: 'zone8' },
	{ Country: 'Jamaica (JM)', Zone: 'zone8' },
	{ Country: 'Kiribati (KI)', Zone: 'zone8' },
	{ Country: 'Mariana Islands (MP)', Zone: 'zone8' },
	{ Country: 'Marshall Islands (MH)', Zone: 'zone8' },
	{ Country: 'Martinique (MQ)', Zone: 'zone8' },
	{ Country: 'Micronesia (FM)', Zone: 'zone8' },
	{ Country: 'Montserrat (MS)', Zone: 'zone8' },
	{ Country: 'Nauru, Rep. Of (NR)', Zone: 'zone8' },
	{ Country: 'Nevis (XN)', Zone: 'zone8' },
	{ Country: 'New Caledonia (NC)', Zone: 'zone8' },
	{ Country: 'New Zealand (NZ)', Zone: 'zone8' },
	{ Country: 'Nicaragua (NI)', Zone: 'zone8' },
	{ Country: 'Niue (NU)', Zone: 'zone8' },
	{ Country: 'Panama (PA)', Zone: 'zone8' },
	{ Country: 'Papua New Guinea (PG)', Zone: 'zone8' },
	{ Country: 'Paraguay (PY)', Zone: 'zone8' },
	{ Country: 'Peru (PE)', Zone: 'zone8' },
	{ Country: 'Puerto Rico (PR)', Zone: 'zone8' },
	{ Country: 'Saint Helena (SH)', Zone: 'zone8' },
	{ Country: 'Samoa (WS)', Zone: 'zone8' },
	{ Country: 'Solomon Islands (SB)', Zone: 'zone8' },
	{ Country: 'St. Barthelemy (XY)', Zone: 'zone8' },
	{ Country: 'St. Eustatius (XE)', Zone: 'zone8' },
	{ Country: 'St. Kitts (KN)', Zone: 'zone8' },
	{ Country: 'St. Lucia (LC)', Zone: 'zone8' },
	{ Country: 'St. Maarten (XM)', Zone: 'zone8' },
	{ Country: 'St. Vincent (VC)', Zone: 'zone8' },
	{ Country: 'Suriname (SR)', Zone: 'zone8' },
	{ Country: 'Tahiti (PF)', Zone: 'zone8' },
	{ Country: 'Tonga (TO)', Zone: 'zone8' },
	{ Country: 'Trinidad And Tobago (TT)', Zone: 'zone8' },
	{ Country: 'Turks & Caicos (TC)', Zone: 'zone8' },
	{ Country: 'Tuvalu (TV)', Zone: 'zone8' },
	{ Country: 'Uruguay (UY)', Zone: 'zone8' },
	{ Country: 'Vanuatu (VU)', Zone: 'zone8' },
	{ Country: 'Venezuela (VE)', Zone: 'zone8' },
	{ Country: 'Virgin Islands-British (VG)', Zone: 'zone8' },
	{ Country: 'Virgin Islands-US (VI)', Zone: 'zone8' },
	{ Country: 'Nigeria (NG)', Zone: 'zone8' },
];
